### PR TITLE
Apply Clang-Format to library files

### PR DESCRIPTION
**Pull request by crtrott**
This will help synchronize changes done in Kokkos

### CODE REVIEW

**Comment by crtrott** [comment]
I literally only applied `clang-format -i`

**Comment by crtrott** [comment]
@trws I think this will make it easier going forward. Any concerns?

**Comment by dalg24** [comment]
What version did you use?

**Comment by dalg24** [comment]
None of the version I tried gave a clean output
```
git ls-files atomics/include | xargs ~/.local/clang+llvm-10.0.0/bin/clang-format -I
git diff --stat

 atomics/include/desul/atomics.hpp                                     |   5 +--
 atomics/include/desul/atomics/Atomic_Ref.hpp                          | 165 +++++++++++++++++++++++++++++---------------------------------------
 atomics/include/desul/atomics/Common.hpp                              |   1 +
 atomics/include/desul/atomics/cuda/cuda_cc7_asm.inc                   |   4 +-
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc   | 376 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------------
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc         | 136 ++++++++++++++++++++++++++++++++++++--------------------
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_exchange.inc          |   4 +-
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_exchange_memorder.inc |   5 +--
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_exchange_op.inc       | 106 ++++++++++++++++++++++++++++++--------------
 atomics/include/desul/atomics/cuda/cuda_cc7_asm_memorder.inc          |   5 +--
 atomics/include/desul/atomics/openmp/OpenMP_40_op.inc                 | 248 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------
 11 files changed, 640 insertions(+), 415 deletions(-)

**Comment by crtrott** [comment]
I used clang-8 (just because its the one we have been using for a while in Kokkos) and I did not apply to .inc files because I don't feel clang-format would improve all the macro shit there.

**Comment by dalg24** [comment]
```
git ls-files atomics/include | grep -v "\.inc" | xargs ~/.local/clang+llvm-8.0.0/bin/clang-format -i

diff --git a/atomics/include/desul/atomics.hpp b/atomics/include/desul/atomics.hpp
index ab3fe25..fd57d19 100644
--- a/atomics/include/desul/atomics.hpp
+++ b/atomics/include/desul/atomics.hpp
@@ -1,4 +1,4 @@
-/*
+/*
 Copyright (c) 2019, Lawrence Livermore National Security, LLC
 and DESUL project contributors. See the COPYRIGHT file for details.
 Source: https://github.com/desul/desul

**Review by dalg24 — DISMISSED** [review]

**Comment by trws** [comment]
> @trws I think this will make it easier going forward. Any concerns?

Only that we pick a clang-format version as @dalg24 mentions, otherwise I think it's 100% positive.

**Comment by trws** [comment]
Hm, if it needs to be 8 that's probably ok.  Things do get somewhat better after that but that's fine for now.

**Comment by trws** [comment]
Once the new check passes, I'd say LGTM.  Then we should make that a required check to merge, maybe even add an easy to activate commit hook?

**Comment by crtrott** [comment]
looks good to me too.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
