### PR TITLE
Optimize min/max atomics

### PR DESCRIPTION
**Pull request by dalg24**
See kokkos/kokkos#3144 for rational and credit to the persons who suggested this change.
This implements a variant of the solution proposed by @jeffhammond

### CODE REVIEW

**Comment by trws** [comment]
I meant to post this question on Thursday when we had the call, but it slipped my mind.  Is there a reason to keep the check out of the loop? This change looks good for short-circuiting the check if the initial value is already too high/low, but it looks like if that fails then it will run until it successfully exchanges a value even if that exchange will have no effect.

**Comment by jeffhammond** [comment]
Makes sense.  I just figured adding a branch to the loop might be imprudent but I guess CPU branch predictors are improving faster than CPU compare-and-swap implementations.

**Comment by jeffhammond** [comment]
I assume you (@trws) implemented what you propose in RAJA already - do you have performance results?

**Comment by trws** [comment]
I [did](https://github.com/LLNL/RAJA/pull/470), it may amuse you to know that I did so at the recommendation and behest of @jcownie-intel in fact from [this issue](https://github.com/LLNL/RAJA/issues/447).  I don't have performance numbers on hand, but Jim's logic was that the number of exchanges required increases logarithmically with contributions if you use early exit, and possibly up to linearly without it.  I recall at the time thinking it might be bad for GPUs, but it turned out that either we were using the hardware atomic anyway, or it was a benefit because the CAS contention on the GPU was *so* much worse anyway that it came out a win at the time.  No tests on this years hardware though, so certainly let me know if this is actually a loss somewhere and we'll tweak it.

**Comment by jeffhammond** [comment]
We can just move the check into the loop in the Kokkos implementation and use that performance test...

**Comment by trws** [comment]
Sounds like a good idea to me.

**Comment by trws** [comment]
Ok, here are some numbers.  In the fashion of the 100% on and off tests, I added a couple of new pathological tests that give maximum contention with similar but constantly changing values.  The time for the original tests doesn't change in any meaningful way on a 6-core `CPUModel="Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz"`, but for a high contention test with substantial overlap it cuts the time roughly in half to put the test inside the loop.

With the check outside the loop:
```
~/build/kokkos/build issue-3144-new* 16s
❯ OMP_PROC_BIND=true OMP_PLACES=threads OMP_NUM_THREADS=12 ./core/perf_test/KokkosCore_PerformanceTest_Atomic_MinMax 100000000
OMP: Info #262: OMP_NESTED variable deprecated, please use OMP_MAX_ACTIVE_LEVELS instead.
================ int
Time for 100% min replacements: 0.0932371
Time for 100% max replacements: 0.100183
Time for 100% max early exits: 0.0172292
Time for 100% min early exits: 0.0178577
Time for rand max replacements: 4.7544
Time for rand min replacements: 4.73018
================ long
Time for 100% min replacements: 0.104825
Time for 100% max replacements: 0.115426
Time for 100% max early exits: 0.0283083
Time for 100% min early exits: 0.0288278
Time for rand max replacements: 5.32822
Time for rand min replacements: 5.31932
================ long long
Time for 100% min replacements: 0.113651
Time for 100% max replacements: 0.114278
Time for 100% max early exits: 0.0294501
Time for 100% min early exits: 0.0318021
Time for rand max replacements: 4.10145
Time for rand min replacements: 3.98802
================ unsigned int
Time for 100% min replacements: 0.108284
Time for 100% max replacements: 0.108583
Time for 100% max early exits: 0.0196566
Time for 100% min early exits: 0.0178775
Time for rand max replacements: 5.0677
Time for rand min replacements: 5.13639
================ unsigned long
Time for 100% min replacements: 0.107673
Time for 100% max replacements: 0.112463
Time for 100% max early exits: 0.0296944
Time for 100% min early exits: 0.0290234
Time for rand max replacements: 4.65963
Time for rand min replacements: 4.6888
================ unsigned long long
Time for 100% min replacements: 0.106691
Time for 100% max replacements: 0.138222
Time for 100% max early exits: 0.0293403
Time for 100% min early exits: 0.0291778
Time for rand max replacements: 4.4757
Time for rand min replacements: 4.4536
================ float
Time for 100% min replacements: 0.144495
Time for 100% max replacements: 0.117629
Time for 100% max early exits: 0.0224888
Time for 100% min early exits: 0.0179903
Time for rand max replacements: 5.04744
Time for rand min replacements: 5.08306
================ double
Time for 100% min replacements: 0.128463
Time for 100% max replacements: 0.121046
Time for 100% max early exits: 0.0299332
Time for 100% min early exits: 0.0306431
Time for rand max replacements: 4.99101
Time for rand min replacements: 5.0567
```

With the check inside the loop:
```
~/build/kokkos/build issue-3144-new* 15s
❯ OMP_PROC_BIND=true OMP_PLACES=threads OMP_NUM_THREADS=12 ./core/perf_test/KokkosCore_PerformanceTest_Atomic_MinMax 100000000
OMP: Info #262: OMP_NESTED variable deprecated, please use OMP_MAX_ACTIVE_LEVELS instead.
================ int
Time for 100% min replacements: 0.0942474
Time for 100% max replacements: 0.098239
Time for 100% max early exits: 0.0185316
Time for 100% min early exits: 0.0189307
Time for rand max replacements: 2.79344
Time for rand min replacements: 2.80132
================ long
Time for 100% min replacements: 0.100572
Time for 100% max replacements: 0.11544
Time for 100% max early exits: 0.0291216
Time for 100% min early exits: 0.0299366
Time for rand max replacements: 2.88375
Time for rand min replacements: 2.96094
================ long long
Time for 100% min replacements: 0.112334
Time for 100% max replacements: 0.119595
Time for 100% max early exits: 0.0299933
Time for 100% min early exits: 0.0317009
Time for rand max replacements: 2.84466
Time for rand min replacements: 2.76863
================ unsigned int
Time for 100% min replacements: 0.107334
Time for 100% max replacements: 0.103198
Time for 100% max early exits: 0.0183176
Time for 100% min early exits: 0.0187303
Time for rand max replacements: 3.0297
Time for rand min replacements: 3.00875
================ unsigned long
Time for 100% min replacements: 0.10767
Time for 100% max replacements: 0.113575
Time for 100% max early exits: 0.028875
Time for 100% min early exits: 0.0291971
Time for rand max replacements: 2.42469
Time for rand min replacements: 2.47012
================ unsigned long long
Time for 100% min replacements: 0.113921
Time for 100% max replacements: 0.108803
Time for 100% max early exits: 0.0321172
Time for 100% min early exits: 0.0291719
Time for rand max replacements: 2.97458
Time for rand min replacements: 2.98217
================ float
Time for 100% min replacements: 0.122749
Time for 100% max replacements: 0.120777
Time for 100% max early exits: 0.0247718
Time for 100% min early exits: 0.0270983
Time for rand max replacements: 3.09006
Time for rand min replacements: 3.08231
================ double
Time for 100% min replacements: 0.121189
Time for 100% max replacements: 0.12224
Time for 100% max early exits: 0.031552
Time for 100% min early exits: 0.0327313
Time for rand max replacements: 2.98827
Time for rand min replacements: 3.01386
```

Here is the test code I appended to get these numbers:

```c++
  // input is min values - some max atomics will replace
  {
    inp(0) = min;
    Kokkos::fence();

    timer.reset();
    T current(0);
    Kokkos::parallel_reduce(
        length,
        KOKKOS_LAMBDA(const int i, T& inner) {
          inner = Kokkos::atomic_max_fetch(&(inp(0)), inner+1);
          if (i == length - 1)
            inner = Kokkos::atomic_max_fetch(&(inp(0)), max);
        },
        current);
    // Kokkos::parallel_for(
    //     length, KOKKOS_LAMBDA(const int i) {
    //       (void)Kokkos::atomic_max_fetch(&(inp(0)), a(i));
    //     });
    Kokkos::fence();
    double time = timer.seconds();

    if (inp(0) < max) {
      std::cerr << "Error in rand max replacements: " << std::endl;
      std::cerr << "inp(0)=" << inp(0) << std::endl;
    }
    std::cout << "Time for rand max replacements: " << time << std::endl;
  }

  // input is max values - some min atomics will replace
  {
    inp(0) = max;
    Kokkos::fence();

    timer.reset();
    T current(100000000);
    Kokkos::parallel_reduce(
        length,
        KOKKOS_LAMBDA(const int i, T& inner) {
          inner = Kokkos::atomic_min_fetch(&(inp(0)), inner-1);
          if (i == length - 1)
            inner = Kokkos::atomic_min_fetch(&(inp(0)), min);
        },
        current);
    Kokkos::fence();
    double time = timer.seconds();

    if (inp(0) > min) {
      std::cerr << "Error in rand min replacements: " << std::endl;
      std::cerr << "inp(0)=" << inp(0) << std::endl;
    }
    std::cout << "Time for rand min replacements: " << time << std::endl;
  }
```

The actual atomic code just moved the check down a couple of lines to be the first line inside the do/while loop.

**Comment by trws** [comment]
Numbers for my workstation, similar but slightly smaller difference: `CPUModel="AMD Ryzen Threadripper 2990WX 32-Core Processor"`

Out of loop:

```
~/build/kokkos/build atomic-rework* scogland1@chimera 11s
❯ OMP_PROC_BIND=true OMP_PLACES=threads OMP_NUM_THREADS=64 ./core/perf_test/KokkosCore_PerformanceTest_Atomic_MinMax 100000000
OMP: Info #262: OMP_NESTED variable deprecated, please use OMP_MAX_ACTIVE_LEVELS instead.
================ int
Time for 100% min replacements: 0.0148402
Time for 100% max replacements: 0.0146685
Time for 100% max early exits: 0.0087883
Time for 100% min early exits: 0.00885584
Time for rand max replacements: 2.65782
Time for rand min replacements: 2.63046
================ long
Time for 100% min replacements: 0.0539509
Time for 100% max replacements: 0.0271288
Time for 100% max early exits: 0.015842
Time for 100% min early exits: 0.0158658
Time for rand max replacements: 2.76064
Time for rand min replacements: 2.6888
================ long long
Time for 100% min replacements: 0.0270114
Time for 100% max replacements: 0.0270864
Time for 100% max early exits: 0.0158485
Time for 100% min early exits: 0.0158464
Time for rand max replacements: 2.74452
Time for rand min replacements: 2.65603
================ unsigned int
Time for 100% min replacements: 0.0144735
Time for 100% max replacements: 0.0147473
Time for 100% max early exits: 0.00840088
Time for 100% min early exits: 0.00837737
Time for rand max replacements: 2.7676
Time for rand min replacements: 2.65329
================ unsigned long
Time for 100% min replacements: 0.0577542
Time for 100% max replacements: 0.0986649
Time for 100% max early exits: 0.0180866
Time for 100% min early exits: 0.23018
Time for rand max replacements: 2.70324
Time for rand min replacements: 2.99472
================ unsigned long long
Time for 100% min replacements: 0.0787553
Time for 100% max replacements: 0.227238
Time for 100% max early exits: 0.0373853
Time for 100% min early exits: 0.0205923
Time for rand max replacements: 2.7513
Time for rand min replacements: 2.72403
================ float
Time for 100% min replacements: 0.0286058
Time for 100% max replacements: 0.0147386
Time for 100% max early exits: 0.00880221
Time for 100% min early exits: 0.00888722
Time for rand max replacements: 3.70563
Time for rand min replacements: 3.62717
================ double
Time for 100% min replacements: 0.0539819
Time for 100% max replacements: 0.0815032
Time for 100% max early exits: 0.0168241
Time for 100% min early exits: 0.0159313
Time for rand max replacements: 3.69718
Time for rand min replacements: 3.71055
```

In loop:

```
~/build/kokkos/build atomic-rework scogland1@chimera 11s
❯ OMP_PROC_BIND=true OMP_PLACES=threads OMP_NUM_THREADS=64 ./core/perf_test/KokkosCore_PerformanceTest_Atomic_MinMax 100000000
OMP: Info #262: OMP_NESTED variable deprecated, please use OMP_MAX_ACTIVE_LEVELS instead.
================ int
Time for 100% min replacements: 0.0141088
Time for 100% max replacements: 0.0142578
Time for 100% max early exits: 0.00878365
Time for 100% min early exits: 0.00881218
Time for rand max replacements: 1.33834
Time for rand min replacements: 1.34355
================ long
Time for 100% min replacements: 0.0268281
Time for 100% max replacements: 0.0268766
Time for 100% max early exits: 0.0158354
Time for 100% min early exits: 0.0157709
Time for rand max replacements: 1.3183
Time for rand min replacements: 1.37035
================ long long
Time for 100% min replacements: 0.0268419
Time for 100% max replacements: 0.0268863
Time for 100% max early exits: 0.0156897
Time for 100% min early exits: 0.0158774
Time for rand max replacements: 1.3301
Time for rand min replacements: 1.36881
================ unsigned int
Time for 100% min replacements: 0.0139542
Time for 100% max replacements: 0.0139802
Time for 100% max early exits: 0.00834916
Time for 100% min early exits: 0.00836606
Time for rand max replacements: 1.33993
Time for rand min replacements: 1.3888
================ unsigned long
Time for 100% min replacements: 0.0695308
Time for 100% max replacements: 0.0267651
Time for 100% max early exits: 0.0150889
Time for 100% min early exits: 0.0150318
Time for rand max replacements: 1.35164
Time for rand min replacements: 1.38029
================ unsigned long long
Time for 100% min replacements: 0.0453789
Time for 100% max replacements: 0.0464274
Time for 100% max early exits: 0.0151494
Time for 100% min early exits: 0.0168497
Time for rand max replacements: 1.39734
Time for rand min replacements: 1.38433
================ float
Time for 100% min replacements: 0.112229
Time for 100% max replacements: 0.0310428
Time for 100% max early exits: 0.152677
Time for 100% min early exits: 0.227962
Time for rand max replacements: 2.3193
Time for rand min replacements: 2.31021
================ double
Time for 100% min replacements: 0.232534
Time for 100% max replacements: 0.225923
Time for 100% max early exits: 0.0415606
Time for 100% min early exits: 0.0158538
Time for rand max replacements: 2.35918
Time for rand min replacements: 2.35995
```

**Comment by jeffhammond** [comment]
Cool.  Inside the loop FTW.  That's an easy change (for someone else, since I'm going to be in slide-making hell for the next week).

**Comment by dalg24** [comment]
Will rebase after we merge #14

**Review by crtrott — APPROVED** [review]

**Pull request merged**
