### PR TITLE
Fixup filename Lock_Array_{Cuda -> CUDA}.hpp

### PR DESCRIPTION
**Pull request by dalg24**
Messed up when cleaning up on a machine with case insensitive file system

### CODE REVIEW

**Comment by masterleinad** [comment]
Why is this better than using the original name `Lock_Array_Cuda.hpp` and changing the include directives accordingly?

**Comment by Rombur** [comment]
Because it's the only one `Cuda`, everywhere else we use `CUDA`

**Comment by dalg24** [comment]
> Why is this better than using the original name `Lock_Array_Cuda.hpp` and changing the include directives accordingly?

Consistency

**Comment by masterleinad** [comment]
I would favor backward compatibility, but I guess that doesn't matter for this repository yet (in particular with respect to https://github.com/desul/desul/pull/69).

**Review by trws — APPROVED** [review]

**Pull request merged**
