### PR TITLE
SYCL: Address oneAPI 2025.0.0 deprecations

### PR DESCRIPTION
**Pull request by masterleinad**
Corresponds to https://github.com/kokkos/kokkos/pull/7196.
The free function queries were moved and deprecated in https://github.com/intel/llvm/pull/13257.

### CODE REVIEW

**Review by dalg24 — APPROVED** [review]
Fine by me

**Comment by dalg24** [comment]
@crtrott @trws any objection to merge this?

**Comment by dalg24** [comment]
> @crtrott @trws any objection to merge this?

Last call

**Comment by trws** [comment]
Works for me.

**Pull request merged**
