### PR TITLE
Drop (unused) `Impl::eliminate_warning_for_lock_array` CUDA/HIP functions

### PR DESCRIPTION
**Pull request by dalg24**
Corresponding to kokkos/kokkos#5786

### CODE REVIEW

**Review by masterleinad — COMMENTED** [review]
Looks good but have you actually tested that there is no warning?

**Comment by dalg24** [comment]
> Looks good but have you actually tested that there is no warning?

What warning?

**Comment by dalg24** [comment]
Rebased onto master after the merge of #90

**Comment by masterleinad** [comment]
> What warning?

It's called `eliminate_warning_for_lock_array` so I suspect there was a warning at some point. 🙂 SInce we are not running unit tests with `Cuda` or `HIP` in the CI, I just want to make sure.

**Comment by dalg24** [comment]
These were clearly copied from Kokkos
https://github.com/kokkos/kokkos/blob/6e73a35407bba14313d30f420f716cb91b566e7d/core/src/Cuda/Kokkos_Cuda_Locks.hpp#L122
were they are also unused :/

**Comment by dalg24** [comment]
Didn't mean to close...

**Pull request closed without merging**
